app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.MonthCalendar.as_view(), name='month'),
    path('month/<int:year>/<int:month>/', views.MonthCalendar.as_view(), name='month'),
    path('week/', views.WeekCalendar.as_view(), name='week'),
    path('week/<int:year>/<int:month>/<int:day>/', views.WeekCalendar.as_view(), name='week'),
    path('week_with_schedule/', views.WeekWithScheduleCalendar.as_view(), name='week_with_schedule'),
    path(
        'week_with_schedule/<int:year>/<int:month>/<int:day>/',
        views.WeekWithScheduleCalendar.as_view(),
        name='week_with_schedule'
    ),
    path(
        'month_with_schedule/',
        views.MonthWithScheduleCalendar.as_view(), name='month_with_schedule'
    ),
    path(
        'month_with_schedule/<int:year>/<int:month>/',
        views.MonthWithScheduleCalendar.as_view(), name='month_with_schedule'
    ),
    path('mycalendar/', views.MyCalendar.as_view(), name='mycalendar'),
    path(
        'mycalendar/<int:year>/<int:month>/<int:day>/', views.MyCalendar.as_view(), name='mycalendar'
    ),
    path(
        'month_with_forms/',
        views.MonthWithFormsCalendar.as_view(), name='month_with_forms'
    ),
    path(
        'month_with_forms/<int:year>/<int:month>/',
        views.MonthWithFormsCalendar.as_view(), name='month_with_forms'
    ),
]

django_calendar/urls.py
from django.conf.urls import url
from django_calendar import views

app_name = 'django_calendar'

urlpatterns = [
    # シンプルなカレンダーページ
    url(r'^$', views.CalendarView.as_view(), name='calendar'),
    url(r'^(?P<year>[0-9]+)/(?P<month>[0-9]+)/$',
        views.CalendarView.as_view(), name='calendar'),
    url(r'^week/(?P<year>[0-9]+)/(?P<month>[0-9]+)/(?P<week>[0-9]+)/$',
        views.WeekCalendarView.as_view(), name='week_calendar'),
    url(
        (
            r'^schedule_create/'
            r'(?P<year>[0-9]+)/(?P<month>[0-9]+)/(?P<day>[0-9]+)/$'
        ),
        views.ScheduleCreateView.as_view(),
        name='schedule_create'),
    url(
        (
            r'^schedule_list/'
            r'(?P<year>[0-9]+)/(?P<month>[0-9]+)/(?P<day>[0-9]+)/$'
        ),
        views.ScheduleListView.as_view(),
        name='schedule_list'),

    # 時間つきカレンダーページ
    url(r'^withtime/$',
        views.WithTimeCalendarView.as_view(), name='withtime_calendar'),
    url(r'^withtime/(?P<year>[0-9]+)/(?P<month>[0-9]+)/$',
        views.WithTimeCalendarView.as_view(),
        name='withtime_calendar'),
    url(
        (
            r'^withtime/week/'
            r'(?P<year>[0-9]+)/(?P<month>[0-9]+)/(?P<week>[0-9]+)/$'
        ),
        views.WithTimeWeekCalendarView.as_view(),
        name='withtime_week_calendar'),
    url(
        (
            r'^withtime/schedule_create/'
            r'(?P<year>[0-9]+)/(?P<month>[0-9]+)/(?P<day>[0-9]+)/$'
        ),
        views.WithTimeScheduleCreateView.as_view(),
        name='withtime_schedule_create'),
    url(
        (
            r'^withtime/schedule_list/'
            r'(?P<year>[0-9]+)/(?P<month>[0-9]+)/(?P<day>[0-9]+)/$'
        ),
        views.WithTimeScheduleListView.as_view(),
        name='withtime_schedule_list'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

django_calendar/models.py
import datetime
from django.db import models
from django.utils import timezone


class Schedule(models.Model):
    """スケジュール."""

    memo = models.TextField('メモ')
    date = models.DateField('日付')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.memo


class WithTimeSchedule(models.Model):
    """時間付きスケジュール."""

    memo = models.TextField('メモ')
    start_time = models.TimeField('開始時間', default=datetime.time(7, 0, 0))
    end_time = models.TimeField('終了時間', default=datetime.time(7, 0, 0))
    date = models.DateField('日付')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.memo

django_calendar/forms.py
from django import forms
from .models import Schedule, WithTimeSchedule


class ScheduleForm(forms.ModelForm):
    """Bootstrapに対応するためのModelForm."""

    class Meta:
        model = Schedule
        fields = ('memo',)
        widgets = {
            'memo': forms.Textarea(attrs={
                'class': 'form-control',
            }),
        }


class WithTimeScheduleForm(forms.ModelForm):
    """Bootstrapに対応するためのModelForm."""

    class Meta:
        model = WithTimeSchedule
        fields = ('memo', 'start_time', 'end_time')
        widgets = {
            'memo': forms.Textarea(attrs={
                'class': 'form-control',
            }),
            'start_time': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'end_time': forms.TextInput(attrs={
                'class': 'form-control',
            }),
        }

    def clean_end_time(self):
        start_time = self.cleaned_data['start_time']
        end_time = self.cleaned_data['end_time']
        if end_time <= start_time:
            raise forms.ValidationError(
                '終了時間は、開始時間よりも後にしてください'
            )
        return end_time

django_calendar/views.py
import datetime
from collections import defaultdict
from django.utils.safestring import mark_safe
from django.views import generic
from django.shortcuts import render

from .calendarlib import (
    SimpleCalendarBS4, WithTimeCalendarBS4,
    TimeScheduleBS4
)
from .forms import ScheduleForm, WithTimeScheduleForm
from .models import Schedule, WithTimeSchedule


class CalendarView(generic.TemplateView):
    """カレンダーを表示するビュー."""

    template_name = 'django_calendar/calendar.html'

    def get_calendar(self, *args, **kwagrs):
        return SimpleCalendarBS4(*args, **kwagrs)

    def get_model(self):
        return Schedule

    def get_context_data(self, *args, **kwargs):
        """カレンダーオブジェクトをcontextに追加する."""
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')

        # /アクセスの場合
        if year is None and month is None:
            date = datetime.datetime.now()

        # yearとmonthの指定がある場合
        elif year and month:
            date = datetime.datetime(
                year=int(year), month=int(month), day=1
            )

        # {1:3, 31:5}のような、日付:スケジュール件数な辞書を作る
        schedule_counter = defaultdict(int)
        queryset = self.get_model().objects.filter(
            date__year=date.year, date__month=date.month
        )
        for schedule in queryset:
            schedule_counter[schedule.date.day] += 1

        month_calendar = self.get_calendar(date, schedule_counter)
        month_calendar_html = month_calendar.formatmonth()
        context = super().get_context_data(*args, **kwargs)

        # mark_safeでhtmlがエスケープされないようにする
        context['calendar'] = mark_safe(month_calendar_html)
        context['date'] = date
        return context


class WeekCalendarView(generic.TemplateView):
    """週間カレンダーのView."""

    template_name = 'django_calendar/week_calendar.html'

    def get_calendar(self, *args, **kwagrs):
        return SimpleCalendarBS4(*args, **kwagrs)

    def get_context_data(self, *args, **kwargs):
        week = self.kwargs.get('week')
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        date = datetime.datetime(
            year=int(year), month=int(month), day=1
        )
        calendar = self.get_calendar(date)
        html = calendar.formatweek_table(int(week))

        context = super().get_context_data(*args, **kwargs)
        context['calendar'] = mark_safe(html)
        context['date'] = date
        return context


class ScheduleCreateView(generic.CreateView):
    """スケジュールの作成ビュー."""

    model = Schedule
    form_class = ScheduleForm

    def form_valid(self, form):
        """スケジュールの日付に、該当の日付を入れて保存する."""
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        day = self.kwargs.get('day')
        date = datetime.datetime(
            year=int(year), month=int(month), day=int(day))
        schedule = form.save(commit=False)
        schedule.date = date
        schedule.save()
        return render(self.request, 'django_calendar/close.html')


class ScheduleListView(generic.ListView):
    """スケジュールの一覧ビュー."""

    model = Schedule

    def get_queryset(self):
        """その日付のスケジュールを返す."""
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        day = self.kwargs.get('day')
        date = datetime.datetime(
            year=int(year), month=int(month), day=int(day)
        )
        queryset = self.model.objects.filter(
            date=date
        )
        return queryset


class WithTimeCalendarView(CalendarView):
    """時間付き月間カレンダーを表示するビュー."""

    template_name = 'django_calendar/withtime_calendar.html'

    def get_calendar(self, *args, **kwagrs):
        return WithTimeCalendarBS4(*args, **kwagrs)

    def get_model(self):
        return WithTimeSchedule


class WithTimeWeekCalendarView(WeekCalendarView):
    """時間付き週間カレンダーを表示するビュー."""

    template_name = 'django_calendar/withtime_week_calendar.html'

    def get_calendar(self, *args, **kwagrs):
        return WithTimeCalendarBS4(*args, **kwagrs)

    def get_model(self):
        return WithTimeSchedule


class WithTimeScheduleCreateView(ScheduleCreateView):
    """時間付きスケジュールの作成ビュー."""

    model = WithTimeSchedule
    form_class = WithTimeScheduleForm
    template_name = 'django_calendar/schedule_form.html'


class WithTimeScheduleListView(ScheduleListView):
    """スケジュールの一覧ビュー."""

    model = WithTimeSchedule

    def get_context_data(self, *args, **kwargs):
        schedules = self.get_queryset().order_by('start_time')
        # 6時から5時
        hours = []
        for x in range(24):
            hour = x + 6
            if hour >= 24:
                hour -= 24
            hours.append(hour)
        time_schedule = TimeScheduleBS4(hours=hours, step=10)
        context = super().get_context_data(*args, **kwargs)
        context['time_schedule'] = mark_safe(
            time_schedule.format_schedule(schedules)
        )
        return context

django_calendar/templates/django_calendar/base.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
  </head>
  <body>
    {% block content %}{% endblock %}

    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    {% block extrajs %}{% endblock %}
  </body>
</html>

django_calendar/templates/django_calendar/calendar.html
{% extends 'django_calendar/base.html' %}
{% block content %}
<style>
.table {
    table-layout: fixed;
}
</style>
    <div class="container">
        {{ calendar }}
    </div>
    
{% endblock %}

django_calendar/templates/django_calendar/close.html
<html>
<head>
</head>
<body>
<script type="text/javascript">
window.opener.location.reload();
window.close();
</script>
</body>
</html>

django_calendar/templates/django_calendar/schedule_form.html
{% extends 'django_calendar/base.html' %}
{% block content %}
<div class="container">
<form action="" method="POST">
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">送信</button>
</form>
</div>
{% endblock %}

django_calendar/templates/django_calendar/schedule_list.html
{% extends 'django_calendar/base.html' %}
{% block content %}
    <div class="container">
        <a href="javascript:void(0);" onclick="window.history.back();">戻る</a>
        {% for schedule in schedule_list %}
            {{ schedule.memo | linebreaks | urlize }}
            <hr>
        {% endfor %}
    </div>
{% endblock %}

django_calendar/templates/django_calendar/week_calendar.html
{% extends 'django_calendar/base.html' %}
{% block content %}
<style>
    .week-table {
        width: 100%;
        max-width: 100%;
        margin-bottom: 1rem;
        table-layout: fixed;
    }
 
    .week-table td {
        border: 1px solid #eceeef;
        vertical-align: top;
    }
    
    .week-table th {
        border: 1px solid #eceeef;
        padding: .75rem;
        vertical-align: top;
    }
 
</style>
    <div class="container">
        <p><a href="{% url 'django_calendar:calendar' date.year date.month %}">月間カレンダーへ</a></p>
        {{ calendar }}
    </div>
    
{% endblock %}

django_calendar/templates/django_calendar/withtime_calendar.html
{% extends 'django_calendar/base.html' %}
{% block content %}
<style>
.table {
    table-layout: fixed;
}
</style>
    <div class="container">
        <p><a href="{% url 'django_calendar:withtime_week_calendar' date.year date.month 1 %}">週間カレンダーへ</a></p>
        {{ calendar }}
    </div>
    
{% endblock %}

django_calendar/templates/django_calendar/withtime_week_calendar.html
{% extends 'django_calendar/base.html' %}
{% block content %}
<style>
    .week-table {
        width: 100%;
        max-width: 100%;
        margin-bottom: 1rem;
        table-layout: fixed;
    }
 
    .week-table td {
        border: 1px solid #eceeef;
        vertical-align: top;
    }
    
    .week-table th {
        border: 1px solid #eceeef;
        padding: .75rem;
        vertical-align: top;
    }
 
</style>
    <div class="container">
        <p><a href="{% url 'django_calendar:withtime_calendar' date.year date.month %}">月間カレンダーへ</a></p>
        {{ calendar }}
    </div>
    
{% endblock %}

django_calendar/templates/django_calendar/withtimeschedule_list.html
{% extends 'django_calendar/base.html' %}
{% block content %}
<style>
    .minute-wrapper {
        border: 1px solid #eceeef;
    }
 
    .hour-name {
        padding: 5px;
        text-align: right;
        border: 1px solid #eceeef;
    }
 
    .just-hour {
        border-top: 1px solid #eceeef;
    }
</style>
    <div class="container">
        <a href="javascript:void(0);" onclick="window.history.back();">戻る</a>
        <hr>
        {{ time_schedule }}
    </div>
{% endblock %}

{% block extrajs %}
<script>
    $(function() {
        $('[data-toggle="tooltip"]').tooltip('show');
    });
</script>
{% endblock %}